return {
  pde = {
    docker = true,
    ansible = true,
    bash = true,
    db = true,
    go = true,
    helm = true,
    html = true,
    json = true,
    yaml = true,
    lua = true,
    protobuf = true,
    python = true,
    rust = true,
    terraform = true,
    typescript = true,
    vuejs = false,
    tailwind = false,
    svelte = false,
    solidty = false,
    react = false,
    java = false,
    csharp = false,
    cpp = false,
    angular = false,
  },
}
