return {
  pde = {
    ansible = true,
    bash = true,
    go = true,
    helm = true,
    html = true,
    json = true,
    lua = true,
    python = true,
    rust = true,
    solidty = true,
    terraform = true,
    vuejs = false,
    typescript = false,
    tailwind = false,
    svelte = false,
    react = false,
    java = false,
    csharp = false,
    cpp = false,
    angular = false,
  },
}
